AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 100

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'
