version: "3.1"

services:
  postgres:
    image: postgres:12.4
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: poker_backend
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    stdin_open: true
    tty: true
