version: "3.1"

services:
  poker_postgres:
    image: postgres:12.4
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: poker_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data
    stdin_open: true
    tty: true
